on:
  push
jobs:
  ubuntu_testing:
    runs-on: ubuntu-latest
    steps:
        - name: Run unit tests
          run: |
              python -m unittest rectangle
              python -m unittest circle
              python -m unittest square
              python -m unittest triangle
  windows_testing:
    runs-on: windoes-latest
    steps:
        - name: Run unit tests
          run: |
              python -m unittest rectangle.py
              python -m unittest circle.py
              python -m unittest square.py
              python -m unittest triangle.py
